### ISSUE TITLE
Issue on page /intro.html - mamba can't create environment from yaml file

### ISSUE THREAD

**Issue by michaeljohnsontv** [fneum/data-science-for-esm#16]
Hi, this command doesn't seem to work:
```mamba create -f environment.yml```

there is an issue with this, documented here: https://github.com/mamba-org/mamba/issues/633
There are a couple of workarounds proposed on this issue page, including one that worked for me - create an empty env with mamba, then update it based on --file environment.yaml

**Comment by exergetiker** [comment]
It's still not fixed. 
The correct command should be:
`mamba env create --file envname.yaml`

**Comment by fneum** [comment]
reverted to `conda`
