### ISSUE TITLE
Improve Intro

### ISSUE THREAD

**Issue by pz-max** [fneum/data-science-for-esm#2]
Add to your intro what this website is about & what people will learn. Basically:
"This semester I taught a new course at TU Berlin on energy system modelling and data science, for which I built a small website with energy-focused Python tutorials. The course offers many hands-on introductions to various libraries that are useful for energy system modelling and processing data more generally. It includes tutorials and examples for getting started with Python, numpy, matplotlib, pandas, geopandas, cartopy, rasterio, atlite, networkx, pyomo, pypsa, plotly, hvplot, and streamlit. Topics covered include:

- time series analysis (e.g. wind and solar production)
- tabular data (e.g. LNG terminals)
- geographical data (e.g. location of power plants)
- data visualisation
- converting weather data to renewable generation
- land eligibility analysis (e.g. where to build wind turbines)
- optimisation 
- electricity market modelling
- power flow modelling (linearised)
- capacity expansion planning
- sector-coupling"
- interactive visualisation and dashboarding"

**Comment by fneum** [comment]
Coming in next commit.
