### ISSUE TITLE
linopy workshop

### ISSUE THREAD

**Issue by pz-max** [fneum/data-science-for-esm#5]
Awesome notebooks! Is there interest to convert the pyomo notebook to a linopy version?
Happy to work on this if you think it's useful

**Comment by fneum** [comment]
Could be nice! But probably running in "dual mode" for a while.

The argument for `pyomo` in the course is that it is currently much more widely used and may be more useful to students.

**Comment by pz-max** [comment]
Cool! Happy to build a replica for Linopy so you can run it in dual mode
-- Linopy will be useful for the PyPSA crowd we like to train :)
