### ISSUE TITLE
update workshop 12 - sector coupling with multilink default

### ISSUE THREAD

**Issue by pz-max** [fneum/data-science-for-esm#7]
Since the PR: https://github.com/PyPSA/PyPSA/pull/669, my feeling is that this code block is not necessary. I am happy to get assigned to this task and deal with it (as well as the Linopy workshop)

*Some sector-coupling technologies have multiple ouputs (e.g. CHP plants producing heat and power). By default, PyPSA links have only one input (bus0) and one output (bus1) with a given efficieny (efficiency). Thus, we have to tell PyPSA that links can have multiple outputs by overriding the component attributes.*
```
override_component_attrs = pypsa.descriptors.Dict(
    {k: v.copy() for k, v in pypsa.components.component_attrs.items()}
)

override_component_attrs["Link"].loc["bus2"] = [
    "string",
    np.nan,
    np.nan,
    "2nd bus",
    "Input (optional)",
]
override_component_attrs["Link"].loc["efficiency2"] = [
    "static or series",
    "per unit",
    1.0,
    "2nd bus efficiency",
    "Input (optional)",
]
override_component_attrs["Link"].loc["p2"] = [
    "series",
    "MW",
    0.0,
    "2nd bus output",
    "Output",
]
```

**Comment by fneum** [comment]
Yes, requires to set minimum PyPSA version in environment yaml.

**Comment by pz-max** [comment]
[like]  Maximilian Parzen reacted to your message:
________________________________

**Comment by pz-max** [comment]
Nice! :+1:
