### ISSUE TITLE
git and github workshop

### ISSUE THREAD

**Issue by pz-max** [fneum/data-science-for-esm#8]
Would it make sense to add a small and concise **introduction to `git` and `github`**?
This introduction aims to teach the `git` concept and the difference between a soft & hard fork. The learning would be especially important for people aiming to join the development e.g. PhDs/ postdocs/professionals/ others. We would refine and extend the course from [here](https://github.com/pypsa-meets-earth/documentation/blob/main/hackathon/0_github_exercise_hands_on.ipynb) to reach the standard of your other offered courses.

Happy to get allocated to this if there is interest.

![image](https://github.com/fneum/data-science-for-esm/assets/61968949/9ae6ff3a-cd1c-4688-b6f7-4c9b5affdc96)

**Comment by fneum** [comment]
I don't plan to cover `git` in the course, and I would reserve this space for aspects that are covered.
